"""
Layer 3: Consistency Checker (Factuality & Plausibility)

This module acts as a final sanity check on the confused text.
It identifies and fixes "fake-sounding" or "diploma mill" entities
generated by the previous masking layers.
"""

from openai import OpenAI

# System prompt for the Content Plausibility Editor
CONSISTENCY_SYSTEM_PROMPT = """You are a Content Plausibility Editor. Your goal is to ensure anonymized stories sound realistic.

Instructions:
1. CHECK the input text for entities (universities, hospitals, companies) that sound like "diploma mills" (野鸡大学), fake, or are logically inconsistent (e.g., a "prestigious" school with a made-up name like "Beijing Medical University").
2. ACTION: If a logical conflict or weird name exists, REPLACE the specific entity name with a Generic Prestigious Placeholder.
   - Example: "Beijing Medical University" -> "a top medical school in Beijing"
   - Example: "Global Tech Solutions Inc." -> "a major tech company"
3. OUTPUT: Return ONLY the corrected text. If the text is already plausible, return it unchanged. Do not explain your edits."""


def check_and_fix_response(text_content, api_key, base_url="https://api.deepseek.com"):
    """
    Check and fix the text for plausibility and factuality.
    
    Args:
        text_content (str): The text to check (usually the confused response)
        api_key (str): DeepSeek API key
        base_url (str): API endpoint URL
        
    Returns:
        str: The fixed/sanitized text
    """
    try:
        if not text_content:
            return text_content
            
        # Initialize OpenAI client
        client = OpenAI(
            api_key=api_key,
            base_url=base_url
        )
        
        # Call the API with the system prompt - Context Isolated (Stateless)
        response = client.chat.completions.create(
            model="deepseek-chat",
            messages=[
                {"role": "system", "content": CONSISTENCY_SYSTEM_PROMPT},
                {"role": "user", "content": text_content}
            ],
            temperature=0.3,  # Low temperature for conservative editing
            max_tokens=1000
        )
        
        fixed_text = response.choices[0].message.content.strip()
        return fixed_text
        
    except Exception as e:
        print(f"Layer 3 Consistency Check failed: {e}")
        # Fail safe: return the input text if check fails
        return text_content
